//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieBuff.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Movie()
        {
            this.tbl_Actor = new HashSet<tbl_Actor>();
        }
    
        public int MovieId { get; set; }
        public string MovieName { get; set; }
        public short YearOfRelease { get; set; }
        public string Plot { get; set; }
        public int ProducerID { get; set; }
        public string PosterData { get; set; }
    
        public virtual tbl_Producer tbl_Producer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Actor> tbl_Actor { get; set; }
    }
}
